import { getModelPricing, costComponent } from "@nullspend/cost-engine";
import type { NewCostEventRow } from "@nullspend/db";
import type { OpenAIUsage } from "./sse-parser.js";

/** Fields auto-generated by the database — excluded from the insert type. */
type CostEventInsert = Omit<NewCostEventRow, "id" | "createdAt">;

/**
 * Map an OpenAI usage object to a cost event ready for persistence.
 *
 * Returns a {@link CostEventInsert} that satisfies `logCostEvent`'s parameter
 * type, making the cost-engine → DB type contract explicit at compile time.
 *
 * Looks up pricing by requestModel first (matches our "openai/gpt-4o" keys).
 * Falls back to responseModel (OpenAI may resolve aliases like gpt-4o → gpt-4o-2024-11-20).
 */
export function calculateOpenAICost(
  requestModel: string,
  responseModel: string | null,
  usage: OpenAIUsage,
  requestId: string,
  durationMs: number,
  attribution?: { userId: string | null; apiKeyId: string | null; actionId: string | null },
): CostEventInsert {
  const promptTokens = Math.max(0, Number(usage.prompt_tokens) || 0);
  const completionTokens = Math.max(0, Number(usage.completion_tokens) || 0);
  const cachedTokens = Math.max(0, Number(usage.prompt_tokens_details?.cached_tokens) || 0);
  const reasoningTokens = Math.max(0, Number(usage.completion_tokens_details?.reasoning_tokens) || 0);

  const normalInputTokens = promptTokens - cachedTokens;

  let pricing = getModelPricing("openai", requestModel);
  let resolvedModel = requestModel;

  if (!pricing && responseModel) {
    pricing = getModelPricing("openai", responseModel);
    if (pricing) resolvedModel = responseModel;
  }

  let costMicrodollars = 0;
  if (pricing) {
    costMicrodollars = Math.round(
      costComponent(normalInputTokens, pricing.inputPerMTok) +
      costComponent(cachedTokens, pricing.cachedInputPerMTok) +
      costComponent(completionTokens, pricing.outputPerMTok),
    );
  }

  return {
    requestId,
    provider: "openai",
    model: resolvedModel,
    inputTokens: promptTokens,
    outputTokens: completionTokens,
    cachedInputTokens: cachedTokens,
    reasoningTokens,
    costMicrodollars,
    durationMs,
    userId: attribution?.userId ?? null,
    apiKeyId: attribution?.apiKeyId ?? null,
    actionId: attribution?.actionId ?? null,
    eventType: "llm" as const,
  };
}
